allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  sharp: false
  unrs-resolver: false
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
